apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api

resources:
- ../../base

images:
- name: pazzii/go-sample-app
  newName: pazzii/go-sample-app
  newTag: sha-4beb9e9c42158876a2d4c52ede731364d8797e5f

replicas:
- count: 3
  name: go-sample-app
