apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api

resources:
- ../../base

images:
- name: pazzii/go-sample-app
  newName: pazzii/go-sample-app
  newTag: sha-b97c6dd171d6177823e4c39d0fd0b770b8020b0c

replicas:
- count: 3
  name: go-sample-app
