apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api

resources:
  - ../../base

images:
  - name: pazzii/go-sample-app
    newTag: "v1.0.0"

replicas:
  - name: go-sample-app
    count: 3
